name: bharat_rescue
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flowder: ^0.2.0
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_svg: ^2.0.7
  geolocator: ^10.0.1
  http: ^1.1.0
  image_picker: ^1.0.4
  latlong2: ^0.9.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
